# Generated by Django 2.2.28 on 2023-05-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_amp_readerid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaderid',
            name='reader_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
